services:
  db:
    container_name: data-society-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Z7m@Q9fK!2xR#P5dWv8N
      POSTGRES_DB: eia_data
    build:
      context: .
      dockerfile: ./db/Dockerfile
    volumes:
      - data-society-db-data:/var/lib/postgresql/data
    ports:
      - "5441:5432"
    networks:
      data-society:
        aliases:
          - data-society-db

  etl:
    container_name: data-society-etl
    build:
      context: .
      dockerfile: ./etl/Dockerfile
      args:
        DB_HOST: data-society-db
        DB_USER: postgres
        DB_PASSWORD: Z7m@Q9fK!2xR#P5dWv8N
        DB_DBNAME: eia_data
        DB_PORT: 5432
    volumes:
      - ./etl/config/:/home/etl-user/config/
      - ./etl/logs/:/home/etl-user/logs/
      - ./etl/jobs/:/home/etl-user/jobs/
      - ./etl/raw_data/:/home/etl-user/raw_data/
      - ./etl/shared/:/home/etl-user/shared/
    #depends_on:
    #  - db
    networks:
      data-society:
        aliases:
          - data-society-etl
    tty: true
    stdin_open: true

networks:
  data-society:
    driver: bridge
    name: data-society

volumes:
  data-society-db-data: